CREATE TABLE IF NOT EXISTS agents_flex_otel_spans (
    id BIGINT NOT NULL AUTO_INCREMENT,
    trace_id CHAR(32) NOT NULL,
    span_id CHAR(16) NOT NULL,
    parent_span_id CHAR(16) NULL,
    trace_flags CHAR(2) NOT NULL,
    trace_state LONGTEXT NULL,
    span_name VARCHAR(255) NOT NULL,
    span_kind VARCHAR(32) NOT NULL,
    start_epoch_nanos BIGINT NOT NULL,
    end_epoch_nanos BIGINT NOT NULL,
    duration_nanos BIGINT NOT NULL,
    status_code VARCHAR(32) NOT NULL,
    status_description VARCHAR(1024) NULL,
    service_name VARCHAR(255) NULL,
    conversation_id VARCHAR(255) NULL,
    account_id VARCHAR(255) NULL,
    scope_name VARCHAR(255) NOT NULL,
    scope_version VARCHAR(64) NULL,
    attributes_json LONGTEXT NOT NULL,
    events_json LONGTEXT NOT NULL,
    links_json LONGTEXT NOT NULL,
    resource_attributes_json LONGTEXT NOT NULL,
    total_attributes INT NOT NULL,
    total_events INT NOT NULL,
    total_links INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_otel_span_identity (trace_id, span_id),
    KEY idx_otel_span_trace (trace_id),
    KEY idx_otel_span_conversation_time (conversation_id, start_epoch_nanos),
    KEY idx_otel_span_account_time (account_id, start_epoch_nanos),
    KEY idx_otel_span_service_time (service_name, start_epoch_nanos),
    KEY idx_otel_span_name_time (span_name, start_epoch_nanos)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agents_flex_otel_metrics (
    id BIGINT NOT NULL AUTO_INCREMENT,
    service_name VARCHAR(255) NULL,
    scope_name VARCHAR(255) NOT NULL,
    scope_version VARCHAR(64) NULL,
    metric_name VARCHAR(255) NOT NULL,
    metric_description VARCHAR(1024) NULL,
    metric_unit VARCHAR(64) NULL,
    metric_type VARCHAR(64) NOT NULL,
    aggregation_temporality VARCHAR(32) NULL,
    monotonic BOOLEAN NULL,
    start_epoch_nanos BIGINT NOT NULL,
    epoch_nanos BIGINT NOT NULL,
    value_long BIGINT NULL,
    value_double DOUBLE NULL,
    point_count BIGINT NULL,
    point_sum DOUBLE NULL,
    point_min DOUBLE NULL,
    point_max DOUBLE NULL,
    attributes_json LONGTEXT NOT NULL,
    data_json LONGTEXT NULL,
    resource_attributes_json LONGTEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_otel_metric_name_time (metric_name, epoch_nanos),
    KEY idx_otel_metric_service_time (service_name, epoch_nanos)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
