/*
 *  Copyright (c) 2023-2026, Agents-Flex (fuhai999@gmail.com).
 *  <p>
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  <p>
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  <p>
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.agentsflex.text2sql.core;

import com.agentsflex.text2sql.entity.DataSourceInfo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SQL Execute Context
 *
 * @author Michael Yang
 */
public class SqlExecuteContext {

    /**
     * Tool name
     */
    private String toolName;

    /**
     * Data source
     */
    private DataSourceInfo dataSource;

    /**
     * Original SQL generated by AI
     */
    private String originalSql;

    /**
     * Current SQL
     * <p>
     * May be modified by interceptors
     */
    private String sql;

    /**
     * SQL parameters
     */
    private List<Object> parameters;

    /**
     * Request ID
     */
    private String requestId;

    /**
     * Start time
     */
    private long startTime;

    /**
     * Extension attributes
     */
    private Map<String, Object> attributes;

    public String getToolName() {
        return toolName;
    }

    public void setToolName(String toolName) {
        this.toolName = toolName;
    }

    public DataSourceInfo getDataSource() {
        return dataSource;
    }

    public void setDataSource(DataSourceInfo dataSource) {
        this.dataSource = dataSource;
    }

    public String getOriginalSql() {
        return originalSql;
    }

    public void setOriginalSql(String originalSql) {
        this.originalSql = originalSql;
    }

    public String getSql() {
        return sql;
    }

    public void setSql(String sql) {
        this.sql = sql;
    }

    public List<Object> getParameters() {
        return parameters;
    }

    public void setParameters(List<Object> parameters) {
        this.parameters = parameters;
    }

    public void addParameter(Object parameter) {
        if (this.parameters == null) {
            this.parameters = new java.util.ArrayList<>();
        }
        this.parameters.add(parameter);
    }

    public void addParameter(Object parameter, int index) {
        if (this.parameters == null) {
            this.parameters = new java.util.ArrayList<>();
        }
        this.parameters.add(index, parameter);
    }

    public void removeParameter(Object parameter) {
        if (this.parameters != null) {
            this.parameters.remove(parameter);
        }
    }

    public void removeParameter(int index) {
        if (this.parameters != null) {
            this.parameters.remove(index);
        }
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public void addAttribute(String key, Object value) {
        if (this.attributes == null) {
            this.attributes = new HashMap<>();
        }
        this.attributes.put(key, value);
    }

    public Object getAttribute(String key) {
        return this.attributes == null ? null : this.attributes.get(key);
    }
}
