/*
 *  Copyright (c) 2023-2026, Agents-Flex (fuhai999@gmail.com).
 *  <p>
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  <p>
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  <p>
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.agentsflex.text2sql.core;

import com.agentsflex.text2sql.entity.DataSourceInfo;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SQL Execute Context
 *
 * @author Michael Yang
 */
public class SqlExecuteContext {

    /**
     * Current tool name
     * e.g. queryDataList/querySingleRow/querySingleValue
     */
    private String toolName;

    /**
     * Data source
     */
    private DataSourceInfo dataSource;

    /**
     * Original SQL generated by AI
     */
    private String originalSql;

    /**
     * SQL after rewriter processing
     */
    private String rewrittenSql;

    /**
     * SQL parameters
     */
    private List<Object> parameters;

    /**
     * Query start time
     */
    private long startTime;

    /**
     * Request trace id
     */
    private String requestId;

    /**
     * Extension attributes
     */
    private Map<String, Object> attributes = new HashMap<>();

    public String getToolName() {
        return toolName;
    }

    public void setToolName(String toolName) {
        this.toolName = toolName;
    }

    public DataSourceInfo getDataSource() {
        return dataSource;
    }

    public void setDataSource(DataSourceInfo dataSource) {
        this.dataSource = dataSource;
    }

    public String getOriginalSql() {
        return originalSql;
    }

    public void setOriginalSql(String originalSql) {
        this.originalSql = originalSql;
    }

    public String getRewrittenSql() {
        return rewrittenSql;
    }

    public void setRewrittenSql(String rewrittenSql) {
        this.rewrittenSql = rewrittenSql;
    }

    public List<Object> getParameters() {
        return parameters;
    }

    public void setParameters(List<Object> parameters) {
        this.parameters = parameters;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public void setAttribute(String key, Object value) {
        this.attributes.put(key, value);
    }

    public Object getAttribute(String key) {
        return this.attributes.get(key);
    }
}
